# Generated by Django 3.0.5 on 2020-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('parameters', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('date_added', models.TextField(max_length=200)),
            ],
        ),
    ]
